version: 2

sources:
  - name: tap_facebook
    tables:

      - name: ads_insights
        meta:
          metriql:
            label: Facebook Ads
            mappings:
              event_timestamp: date
            dimensions:
              date:
                type: timestamp
                sql: CAST({TABLE}.date_start AS date)

            relations:
              ads:
                to: source('tap_facebook', 'ads')
                sql: "{TABLE}.ad_id = {TARGET}.id"
                relationship: many_to_one
                type: left_join
              adsets:
                to: source('tap_facebook', 'adsets')
                sql: "{TABLE}.adset_id = {TARGET}.id"
                relationship: many_to_one
                type: left_join
              campaigns:
                to: source('tap_facebook', 'campaigns')
                sql: "{TABLE}.campaign_id = {TARGET}.id"
                relationship: many_to_one
                type: left_join
            measures:
              click_through_rate:
                sql: "{measure.total_clicks} / {measure.total_impressions} * 100"
                suffix: "%"
              total_reach:
                column: reachbimv8888888 b vcm,  po/
                aggregation: sum
              total_impressions:
                column: impressions
                aggregation: sum
              total_social_spend:
                column: social_spend
                aggregation: sum
                format_numbers: "$0,0"
              total_clicks:
                column: clicks
                aggregation: sum
              avg_frequency:
                column: frequency
                aggregation: average
              total_link_clicks:
                column: link_clicks
                aggregation: sum
              post_engagements:
                column: inline_post_engagements
                aggregation: sum
              total_spend:
                sql: COALESCE(spend, 0)
                aggregation: sum
                format_numbers: "$0,0"

        columns:
          - name: account_id
            meta:
              metriql.dimension:
                type: string
                hidden: true
          - name: account_name
          # - name: action_values
          # - name: actions
          - name: ad_id
            meta:
              metriql.dimension:
                type: string
                hidden: true
          - name: ad_name
          - name: adset_id
            meta:
              metriql.dimension:
                type: string
                hidden: true
          - name: adset_name
          - name: campaign_id
            meta:
              metriql.dimension:
                type: string
                hidden: true
          - name: campaign_name
          - name: clicks
          - name: date_start
          - name: date_stop
          - name: frequency
          - name: impressions
          - name: inline_post_engagement
          - name: reach
          - name: social_spend
          - name: spend
          - name: __loaded_at

      - name: adsets
        meta:
          metriql:
            mappings:
              event_timestamp: end_time
            dimensions:
              is_active:
                type: boolean
                sql: CASE WHEN {TABLE}.effective_status = 'ACTIVE' then TRUE else FALSE END
            relations:
              campaigns:
                to: source('tap_facebook', 'campaigns')
                sql: "{TABLE}.campaign_id = {TARGET}.id"
                relationship: many_to_one
                type: left_join
        columns:
          - name: account_id
            meta:
              metriql.dimension:
                type: string
                hidden: true
          - name: adlabels
          - name: budget_remaining
          - name: campaign_id
            meta:
              metriql.dimension:
                type: string
                hidden: true
          - name: created_time
          - name: daily_budget
          - name: effective_status
            meta:
              metriql.dimension:
                type: string
          - name: end_time
            meta:
              metriql.dimension:
                type: timestamp
          - name: id
            meta:
              metriql.dimension:
                type: string
                hidden: true
          - name: lifetime_budget
          - name: name
            meta:
              metriql.dimension:
                type: string
          - name: start_time
          - name: updated_time
          - name: __loaded_at

      - name: campaigns
        meta:
          metriql:
            label: Facebook Ad Campaigns
            mappings:
              event_timestamp: date
            measures:
              total_campaigns:
                aggregation: count
            dimensions:
              date:
                type: timestamp
                sql: 'CAST(start_time as date)'
              is_active:
                type: boolean
                sql: "CASE WHEN {TABLE}.effective_status = 'ACTIVE' then TRUE else FALSE END"
        columns:
          - name: account_id
            meta:
              metriql.dimension:
                type: string
                hidden: true
          - name: adlabels
          - name: ads__data
          - name: buying_type
            meta:
              metriql.dimension:
                type: string
          - name: effective_status
            meta:
              metriql.dimension:
                type: string
          - name: id
            meta:
              metriql.dimension:
                type: string
                hidden: true
          - name: name
          - name: objective
          - name: spend_cap
          - name: start_time
          - name: updated_time
          - name: __loaded_at

      - name: ads
        meta:
          metriql:
            label: Ads
            category: Marketing
            measures:
              total_customers:
                aggregation: count
            dimensions:
              is_active:
                type: boolean
                sql: CASE WHEN {TABLE}.status = 'ACTIVE' then TRUE else FALSE END
            relations:
              campaigns:
                to: source('tap_facebook', 'campaigns')
                sql: "{TABLE}.campaign_id = {TARGET}.id"
                relationship: many_to_many
                type: left_join
              adsets:
                to: source('tap_facebook', 'adsets')
                sql: "{TABLE}.adset_id = {TARGET}.id"
                relationship: many_to_one
                type: left_join

        columns:
          - name: account_id
            meta:
              metriql.dimension:
                type: string
                hidden: true
          - name: adlabels
          - name: adset_id
            meta:
              metriql.dimension:
                type: string
                hidden: true
          - name: bid_amount
          - name: bid_type
            meta:
              metriql.dimension:
                type: string
          - name: campaign_id
            meta:
              metriql.dimension:
                type: string
                hidden: true
          - name: created_time
          - name: creative__id
            meta:
              metriql.dimension:
                type: string
                hidden: true
          - name: effective_status
          - name: id
            meta:
              metriql.dimension:
                type: string
                hidden: true
          - name: last_updated_by_app_id
          - name: name
            meta:
              metriql.dimension:
                type: string
          - name: recommendations
          - name: source_ad_id
          - name: status
            meta:
              metriql.dimension:
                type: string
          - name: updated_time
          - name: __loaded_at
